apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: iad.ocir.io/aiapps0/helm_charts_poc/mvn-rest:latest
      imagePullSecrets:
      — name: my-secret-aiapps0
